"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api, type SeriesDetail } from "@/lib/api";

function scoreColor(score: number) {
  if (score >= 0.90) return "var(--green)";
  if (score >= 0.75) return "var(--amber)";
  return "var(--red)";
}

function SeriesCard({ series }: { series: SeriesDetail }) {
  return (
    <div
      className="card p-5 space-y-4"
      data-testid={`series-card-${series.series_id}`}
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <div className="space-y-1">
          <h2 className="font-semibold text-base" style={{ color: "var(--text)" }}>
            {series.theme}
          </h2>
          <div className="flex items-center gap-2 text-xs" style={{ color: "var(--text-dim)" }}>
            <span
              className="badge"
              style={{
                background: series.status === "completed" ? "rgba(16,185,129,0.12)" : "rgba(124,133,162,0.12)",
                color: series.status === "completed" ? "var(--green)" : "var(--text-muted)",
              }}
            >
              {series.status}
            </span>
            <span>·</span>
            <span>{new Date(series.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span>
          </div>
        </div>
        <span className="badge badge-purple shrink-0">
          {series.posts.length} part{series.posts.length !== 1 ? "s" : ""}
        </span>
      </div>

      {/* Parts list */}
      {series.posts.length > 0 && (
        <ol className="space-y-2 list-none p-0 m-0">
          {series.posts.map((post) => (
            <li key={post.run_id}>
              <Link
                href={`/posts/${post.run_id}`}
                data-testid={`series-part-${post.run_id}`}
                className="flex items-center gap-3 px-3 py-2 rounded-md transition-colors group"
                style={{
                  background: "rgba(124,133,162,0.05)",
                  border: "1px solid var(--border)",
                  textDecoration: "none",
                }}
              >
                <span
                  className="text-xs shrink-0 tabular-nums font-mono"
                  style={{ color: "#a78bfa", minWidth: "1.5rem" }}
                >
                  #{post.series_position}
                </span>
                <span
                  className="flex-1 text-sm truncate group-hover:text-white transition-colors"
                  style={{ color: "var(--text)" }}
                >
                  {post.title}
                </span>
                {post.quality_score !== undefined && (
                  <span
                    className="text-xs tabular-nums font-semibold shrink-0"
                    style={{ color: scoreColor(post.quality_score) }}
                  >
                    {Math.round(post.quality_score * 100)}
                  </span>
                )}
                <span className="text-xs shrink-0" style={{ color: "var(--text-dim)" }}>→</span>
              </Link>
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}

export default function SeriesPage() {
  const [series, setSeries]   = useState<SeriesDetail[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.listSeries()
      .then(setSeries)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <h1
          className="text-2xl font-bold"
          data-testid="page-heading"
          style={{ color: "#fff" }}
        >
          Series
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>
          Multi-part article series generated by the pipeline.
        </p>
      </div>

      {loading ? (
        <div className="space-y-3">
          {[1, 2].map((i) => (
            <div key={i} className="card p-5 space-y-3">
              <div className="skeleton h-4 w-1/2" />
              <div className="skeleton h-3 w-1/4" />
              <div className="space-y-2">
                <div className="skeleton h-8 w-full" />
                <div className="skeleton h-8 w-full" />
              </div>
            </div>
          ))}
        </div>
      ) : series.length === 0 ? (
        <div className="card p-12 text-center space-y-4" data-testid="empty-state">
          <p className="text-lg" style={{ color: "var(--text-muted)" }}>No series yet</p>
          <p className="text-sm" style={{ color: "var(--text-dim)" }}>
            Run a series pipeline to generate multi-part articles.
          </p>
          <Link
            href="/pipeline"
            className="btn btn-primary inline-block mt-2"
            style={{ textDecoration: "none" }}
          >
            Run Pipeline
          </Link>
        </div>
      ) : (
        <div className="space-y-4">
          {series.map((s) => <SeriesCard key={s.series_id} series={s} />)}
        </div>
      )}
    </div>
  );
}
