from typing import Any, Dict


async def title_optimization_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Generates 3–5 optimised title variants and selects the strongest one.

    The Story (El Relato):
    In the story of our pipeline, this node is the Headline Editor.
    A post's title is the single most critical factor for earning clicks on Medium.
    Rather than relying on the first title generated by the writer, this node analyzes
    the full article draft and the refined editorial angle. It generates multiple
    compelling alternative title options, critiques them for clarity and hook potential,
    and replaces the draft title with the highest-scoring candidate.

    The Flow (El Flujo):
    1. Retrieve the current draft post and editorial brief from the state.
    2. Extract the original title, body content, and refined editorial angle.
    3. Run `run_title_optimization` using the optimization agent.
    4. Set the post's title to the highest-scoring title.
    5. Log the transformation, showing the original title and the winner, along with the variants.
    6. Return the updated post and title variants. Fall back gracefully to the original title if an error occurs.

    Args:
        state: Pipeline state with "post", "topic_brief", and "run_id".

    Returns:
        Dict with "post" (updated title), "title_variants" (list of candidate
        title strings), and "completed_steps". Returns empty dict on exception
        so the pipeline keeps the original title.
    """
    from app.agents.orchestrator import log_step, run_title_optimization

    run_id = state["run_id"]
    post = state.get("post")
    if not post:
        return {}

    topic_brief: dict[str, Any] | None = state.get("topic_brief")
    refined_angle = (topic_brief or {}).get("refined_angle", "") if topic_brief else ""

    await log_step(
        run_id,
        "title_optimizer",
        f'Optimising title: "{post.title}"...',
        data={"original_title": post.title},
    )

    try:
        result = await run_title_optimization(
            run_id=run_id,
            title=post.title,
            content=post.content,
            refined_angle=refined_angle or "",
        )

        original_title = post.title
        post.title = result.best_title
        title_variants = [v.text for v in result.variants]

        await log_step(
            run_id,
            "title_optimizer",
            f'Title optimised: "{original_title}" → "{result.best_title}" '
            f"({len(result.variants)} variants generated)",
            level="success",
            data={
                "original_title": original_title,
                "best_title": result.best_title,
                "variants": title_variants,
                "original_title_weakness": result.original_title_weakness,
            },
        )

        return {
            "post": post,
            "title_variants": title_variants,
            "completed_steps": ["title_optimization"],
        }
    except Exception as e:
        await log_step(
            run_id,
            "title_optimizer",
            f"Title optimization skipped: {e} — keeping original title",
            level="warning",
        )
        return {}
